SELECT ID,
 FECHA ,
 CODIGO_CLIENTE, 
 CODIGO_PRODUCTO, 
 DIRECCION_DOMICILIO,
 PLACA_VEHICULO, 
 PRECIO_DOMICILIO,
 PORCENTAJE_DESCUENTO,
 PRECIO_COMPRA,
 PRECIO_TOTAL,
 APLICA_PROMOCION  
FROM PEDIDO  
ORDER BY CODIGO_CLIENTE,
FECHA;
