SELECT ID,
 FECHA ,
 CODIGO_CLIENTE, 
 CODIGO_PRODUCTO, 
 DIRECCION_DOMICILIO,
 PLACA_VEHICULO, 
 PRECIO_DOMICILIO, 
 PRECIO_TOTAL_COMPRA  FROM pedido  
ORDER BY FECHA, 
CODIGO_CLIENTE, 
CODIGO_PRODUCTO, 
PLACA_VEHICULO, 
PRECIO_TOTAL_COMPRA