SELECT ID,
 FECHA ,
 CODIGO_CLIENTE, 
 CODIGO_PRODUCTO, 
 DIRECCION_DOMICILIO,
 PLACA_VEHICULO,
 PRECIO_COMPRA,
 PORCENTAJE_DESCUENTO,
 PORCENTAJE_PROMOCION,
 PRECIO_TOTAL
FROM PEDIDO
ORDER BY CODIGO_CLIENTE,
FECHA;
