server:
   port: 8083
   servlet:
      context-path: /venta-comida-domicilio
      session:
         timeout: 21600s

spring:
   datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
      
      jdbcUrl: jdbc:mysql://192.168.1.13:3308/delivery_comida

      username: root
      password: root
      hikari:
         poolName: pool
